# Generated by Django 2.0.5 on 2018-05-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_result_tests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test',
            new_name='tests',
        ),
    ]
